# Generated by Django 4.2.3 on 2023-08-02 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='boards',
            field=models.ManyToManyField(to='base.board'),
        ),
        migrations.AlterField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='categories',
            field=models.ManyToManyField(to='base.category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
