# Generated by Django 4.2.3 on 2023-08-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_boards_alter_article_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='users',
        ),
    ]
