# Generated by Django 4.2.3 on 2023-07-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_feed_favorit_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='board',
        ),
    ]
