# Generated by Django 4.2.3 on 2023-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_user_alter_article_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
    ]
