# Generated by Django 4.2.3 on 2023-07-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_feed_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='base.board'),
        ),
    ]
