# Generated by Django 4.2.3 on 2023-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_category_favorit_remove_feed_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(default='Feed'),
            preserve_default=False,
        ),
    ]
