# Generated by Django 4.2.3 on 2023-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='favorit',
            field=models.BooleanField(default=False),
        ),
    ]
